const { chromium } = require('/Users/alfonsomoreno/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert = require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 const page=await browser.newPage({viewport:{width:1024,height:900}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('file:///private/tmp/terra-preview.html');
 const frame=page.frameLocator('iframe');
 await frame.locator('#terra-quotes button').click();
 assert.match(await frame.locator('#terra-detail').innerText(),/1\.218\.560/);
 await frame.locator('[data-status="Aceptada"]').click();
 assert.equal(await frame.locator('#terra-detail .terra-badge').innerText(),'Aceptada');
 await frame.locator('[data-action="duplicate"]').click();
 await frame.locator('#terra-discount-type').selectOption('fixed');
 await frame.locator('#terra-discount').fill('256000');
 assert.match(await frame.locator('#terra-totals').innerText(),/1\.218\.560/);
 await frame.locator('[data-action="add"]').click();
 const last=frame.locator('[data-item]').last();
 await last.locator('[data-field="name"]').fill('Dos equipos de apoyo');
 await last.locator('[data-field="mode"]').selectOption('resource');
 await last.locator('[data-field="qty"]').fill('2');
 await last.locator('[data-field="price"]').fill('150000');
 await last.locator('[data-field="duration"]').fill('3');
 assert.equal(await last.locator('[data-line-total]').innerText(),'$900.000');
 await last.locator('[data-field="global"]').check();
 await frame.locator('#terra-duration').fill('4');
 assert.equal(await frame.locator('[data-item]').last().locator('[data-line-total]').innerText(),'$1.200.000');
 await frame.locator('[data-action="save"]').click();
 assert.equal(await frame.locator('#terra-quotes tr').count(),2);
 await page.screenshot({path:'/Users/alfonsomoreno/Developer/terra/design/prototype-desktop.png',fullPage:true});
 await page.setViewportSize({width:360,height:850});
 await frame.locator('[data-page="settings"]').first().click();
 const overflow=await frame.locator('#terra-prototype').evaluate(e=>e.scrollWidth>e.clientWidth+1);
 assert.equal(overflow,false,'No debe desbordar en móvil');
 await page.screenshot({path:'/Users/alfonsomoreno/Developer/terra/design/prototype-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
 await browser.close();
 console.log('Verificado: ejemplo, aceptación, duplicación, descuentos equivalentes, recursos/días, guardado local, móvil y consola.');
})().catch(e=>{console.error(e);process.exit(1)});
